services:
  postgres:
    image: postgres:17-alpine
    container_name: psgr
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=mydata
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dbnet

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - dbnet
    links:
      - "postgres:db" 
    depends_on:
      - postgres

  webflask:
    build: ./flaskprj
    image: flask-back
    container_name: flsite
    ports:
      - "127.0.0.1:8000:4000" 
    networks:
      - dbnet
    links:
      - "postgres:dbps" 
    depends_on:
      - postgres
    volumes:
      - ./flaskprj:/app
networks:
  dbnet:
    driver: bridge

volumes:
  postgres-data:
